### PR TITLE
use deque for _rxbuf to avoid the vector erase() moving too much memo…

### PR DESCRIPTION
**Pull request by cvoica**
testing to see if this solution will work

### CODE REVIEW

**Comment by bsergean** [comment]
There were a lot of failures on the PR checks.

**Comment by cvoica** [comment]
I work on Linux and I'm happy yo see that at least those tests were fine as I currently use it without any issues on alinux.

After a brief look at Windows logs errors, like TLS support, I remeber this was a compilation flag missing in Linux too.

I will have an in-depth look tomorrow.

**Comment by bsergean** [comment]
Sounds good no rush.

**Comment by bsergean** [comment]
hey let's close this, it is pretty inactive.

**Pull request closed without merging**
