### PR TITLE
add more time to let client close

### PR DESCRIPTION
**Pull request by Kumamon38**

### CODE REVIEW

**Comment by bsergean** [comment]
The linux ci still failed -> https://travis-ci.org/machinezone/IXWebSocket/jobs/531879796

**Comment by bsergean** [comment]
I think the best way is to use condition variables that gets notified when things are ready, instead of adding ix::msleep()

**Comment by Kumamon38** [comment]
Anyway it’s strange to have only 1 ping here whereas we should have 2 for a piece of time

**Comment by bsergean** [comment]
Merged this but that test is disabled now. Maybe we could have a branch with those tests enabled, and try to fix things there.

**Pull request merged**
