### PR TITLE
fix ping, fix send frame close

### PR DESCRIPTION
**Pull request by Kumamon38**
- Fix ping timeout
- Fix an issue about callback/code read from remote.
When we close the connection using close(code, reason...), a CLOSE frame is sent to the remote, and then right after we really close the socket connection. On the remote side, the CLOSE frame data are read, then the connection is immediately closed so the close callback is called with 1006 / Abnormal close instead of the values of the CLOSE frame, because these data are not processed in the dispatch yet. The fix is to close the connection, set that we need to read the buffer, and if nothing triggered a CLOSED state with the data read, then call the callback with 1006 / Abnormal close

### CODE REVIEW

**Comment by Kumamon38** [comment]
Great, so now I have found what was causing the waiting forever in the tests, it's fixed. But I'm getting the same strange TSAN errors on linux gcc as our branch. Seems like we will need to fix that.
More over it occurs just after `Run 8:` of the IXWebSocketTestConnectionDisconnection.cpp

**Comment by bsergean** [comment]
Also I have some other deadlines those days but whenever I'll be able to focus more on this I'll try to look into this TSAN error.

**Comment by Kumamon38** [comment]
No problem, I don’t know when I could have a look next time myself too. What is interesting is that it is the same error as the server, but it is occurring on the client here, and it is exactly the same on docket Ubuntu as on Travis. And in the running test, it occurs only on run 8 over the 20.

**Comment by Kumamon38** [comment]
I am wondering if optimization in O2 or O1 would change the tsan output

**Comment by bsergean** [comment]
Maybe. You could try changing the cmake bits in the unittest (see run.py) to turn on or off debug builds and see.

**Comment by Kumamon38** [comment]
I’ll give a try on Thursday

**Comment by Kumamon38** [comment]
I switched from Debug to Release to test, my Tsan errors are gone but there are new ones on DNSLookup resolve and run
It's quite strange

**Comment by Dimon4eg** [comment]
so we need to fix races on `DNSLookup`

**Comment by Kumamon38** [comment]
```
==================
WARNING: ThreadSanitizer: data race (pid=792)
  Read of size 8 at 0x7d1c0000a7f8 by thread T2:
    #0 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (ix::DNSLookup::*)(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)> (ix::DNSLookup*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)> >::_M_run() <null> (ixwebsocket_unittest+0x0000004fcc61)
    #1 <null> <null> (libstdc++.so.6+0x0000000b8c7f)

  Previous write of size 8 at 0x7d1c0000a7f8 by thread T1 (mutexes: write M141):
    #0 operator new(unsigned long) <null> (libtsan.so.0+0x000000025a33)
    #1 ix::DNSLookup::resolveAsync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&) <null> (ixwebsocket_unittest+0x0000004fc011)
    #2 ix::DNSLookup::resolve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&, bool) <null> (ixwebsocket_unittest+0x0000004fc845)
    #3 ix::SocketConnect::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&) <null> (ixwebsocket_unittest+0x0000004fa65d)
    #4 ix::SocketOpenSSL::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&) <null> (ixwebsocket_unittest+0x00000053101d)
    #5 ix::WebSocketHandshake::clientHandshake(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) <null> (ixwebsocket_unittest+0x00000051adcc)
    #6 ix::WebSocketTransport::connectToUrl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) <null> (ixwebsocket_unittest+0x00000050b136)
    #7 ix::WebSocket::connect(int) <null> (ixwebsocket_unittest+0x000000500915)
    #8 ix::WebSocket::reconnectPerpetuallyIfDisconnected() <null> (ixwebsocket_unittest+0x000000501f4b)
    #9 ix::WebSocket::run() <null> (ixwebsocket_unittest+0x0000005034dc)
    #10 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (ix::WebSocket::*)()> (ix::WebSocket*)> >::_M_run() <null> (ixwebsocket_unittest+0x000000503716)
    #11 <null> <null> (libstdc++.so.6+0x0000000b8c7f)

  Location is heap block of size 112 at 0x7d1c0000a790 allocated by thread T1:
    #0 operator new(unsigned long) <null> (libtsan.so.0+0x000000025a33)
    #1 ix::DNSLookup::resolveAsync(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&) <null> (ixwebsocket_unittest+0x0000004fc011)
    #2 ix::DNSLookup::resolve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&, bool) <null> (ixwebsocket_unittest+0x0000004fc845)
    #3 ix::SocketConnect::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&) <null> (ixwebsocket_unittest+0x0000004fa65d)
    #4 ix::SocketOpenSSL::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&) <null> (ixwebsocket_unittest+0x00000053101d)
    #5 ix::WebSocketHandshake::clientHandshake(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) <null> (ixwebsocket_unittest+0x00000051adcc)
    #6 ix::WebSocketTransport::connectToUrl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) <null> (ixwebsocket_unittest+0x00000050b136)
    #7 ix::WebSocket::connect(int) <null> (ixwebsocket_unittest+0x000000500915)
    #8 ix::WebSocket::reconnectPerpetuallyIfDisconnected() <null> (ixwebsocket_unittest+0x000000501f4b)
    #9 ix::WebSocket::run() <null> (ixwebsocket_unittest+0x0000005034dc)
    #10 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (ix::WebSocket::*)()> (ix::WebSocket*)> >::_M_run() <null> (ixwebsocket_unittest+0x000000503716)
    #11 <null> <null> (libstdc++.so.6+0x0000000b8c7f)

  Mutex M141 (0x7d2c0000afd8) created at:
    #0 pthread_mutex_lock <null> (libtsan.so.0+0x000000037286)
    #1 ix::SocketOpenSSL::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&) <null> (ixwebsocket_unittest+0x000000530fed)
    #2 ix::WebSocketHandshake::clientHandshake(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) <null> (ixwebsocket_unittest+0x00000051adcc)
    #3 ix::WebSocketTransport::connectToUrl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) <null> (ixwebsocket_unittest+0x00000050b136)
    #4 ix::WebSocket::connect(int) <null> (ixwebsocket_unittest+0x000000500915)
    #5 ix::WebSocket::reconnectPerpetuallyIfDisconnected() <null> (ixwebsocket_unittest+0x000000501f4b)
    #6 ix::WebSocket::run() <null> (ixwebsocket_unittest+0x0000005034dc)
    #7 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (ix::WebSocket::*)()> (ix::WebSocket*)> >::_M_run() <null> (ixwebsocket_unittest+0x000000503716)
    #8 <null> <null> (libstdc++.so.6+0x0000000b8c7f)

  Thread T2 (tid=795, running) created by thread T1 at:
    #0 pthread_create <null> (libtsan.so.0+0x000000027577)
    #1 std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) <null> (libstdc++.so.6+0x0000000b8dc2)
    #2 ix::DNSLookup::resolve(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&, bool) <null> (ixwebsocket_unittest+0x0000004fc845)
    #3 ix::SocketConnect::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&) <null> (ixwebsocket_unittest+0x0000004fa65d)
    #4 ix::SocketOpenSSL::connect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::function<bool ()> const&) <null> (ixwebsocket_unittest+0x00000053101d)
    #5 ix::WebSocketHandshake::clientHandshake(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, int) <null> (ixwebsocket_unittest+0x00000051adcc)
    #6 ix::WebSocketTransport::connectToUrl(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int) <null> (ixwebsocket_unittest+0x00000050b136)
    #7 ix::WebSocket::connect(int) <null> (ixwebsocket_unittest+0x000000500915)
    #8 ix::WebSocket::reconnectPerpetuallyIfDisconnected() <null> (ixwebsocket_unittest+0x000000501f4b)
    #9 ix::WebSocket::run() <null> (ixwebsocket_unittest+0x0000005034dc)
    #10 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (ix::WebSocket::*)()> (ix::WebSocket*)> >::_M_run() <null> (ixwebsocket_unittest+0x000000503716)
    #11 <null> <null> (libstdc++.so.6+0x0000000b8c7f)

  Thread T1 'wss://google.co' (tid=794, running) created by main thread at:
    #0 pthread_create <null> (libtsan.so.0+0x000000027577)
    #1 std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) <null> (libstdc++.so.6+0x0000000b8dc2)
    #2 (anonymous namespace)::IXWebSocketTestConnectionDisconnection::start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) <null> (ixwebsocket_unittest+0x0000004efadf)
    #3 ____C_A_T_C_H____T_E_S_T____0() <null> (ixwebsocket_unittest+0x0000004f005c)
    #4 Catch::RunContext::invokeActiveTestCase() <null> (ixwebsocket_unittest+0x000000412f67)
    #5 Catch::(anonymous namespace)::runTests(std::shared_ptr<Catch::Config> const&) [clone .constprop.1880] <null> (ixwebsocket_unittest+0x000000452b03)
    #6 Catch::Session::runInternal() <null> (ixwebsocket_unittest+0x000000454eed)
    #7 Catch::Session::run() <null> (ixwebsocket_unittest+0x000000455054)
    #8 main <null> (ixwebsocket_unittest+0x0000004084cd)

SUMMARY: ThreadSanitizer: data race ??:0 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (ix::DNSLookup::*)(unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)> (ix::DNSLookup*, unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)> >::_M_run()
==================
==================
```
Seeing race like this it makes no sense for me

**Comment by Kumamon38** [comment]
Going back on Debug with my TSAN errors, I may have found something: the data race seems to happen the first time the thread has enough time to successfully connect (after handshake). After the successful, it's ok, and before each attempts stopped before success, it's ok too; so that happen during loop index 8.
If we reduce the test to this:
```
SECTION("Try to connect to invalid servers.")
    {
        IXWebSocketTestConnectionDisconnection chatA;
        // not enough time to connect
        chatA.start(WEBSOCKET_DOT_ORG_URL);
        ix::msleep(7*50);
        chatA.stop();
        // enough time to connect
        chatA.start(WEBSOCKET_DOT_ORG_URL);
        ix::msleep(8*50);
        chatA.stop();
    }
```
the error will appear

**Comment by Kumamon38** [comment]
Maybe there is something wrong with setting the _socket or pending task or whatever

**Comment by Kumamon38** [comment]
Now the problem is found on master, I changed back my tests to master's one. We can finally merge this PR :)

**Comment by bsergean** [comment]
Merging !!

**Comment by bsergean** [comment]
Just got a CI failure -> https://travis-ci.com/machinezone/IXWebSocket/jobs/198950584

**Comment by Kumamon38** [comment]
Yes, I think this come from the CI that make more or less time to connect and then have effects on the tests. You could try to wait for 2700ms and then 400ms (instead of 2900 and 200), I can’t do it myself now sorry as I’m not at the office anymore.


Envoyé de mon iPhone

**Comment by bsergean** [comment]
No worries. I just pushed the small change (2900 -> 2700) that you were suggesting, we'll see if it helps.

**Pull request merged**
