### PR TITLE
Extend vcpkg docs

### PR DESCRIPTION
**Pull request by liz3**
Adds linking instructions for cmake when using vcpkg

### CODE REVIEW

**Comment by bsergean** [comment]
9.6.2 is available on vcpkg now fyi.

**Comment by liz3** [comment]
@bsergean yes, i updated my vcpkg installation and it also uses 9.6.2.

But even after specifying openssl it seams its still including mbdedtls.
Do i need to explicitly exclude mbded tls? 
image

**Comment by bsergean** [comment]
... so I must have messed up something, but I'm afraid I've reached my vcpkg knowledge limits.

1. Can you ask over there ? Maybe they have an FAQ or a forum or something
2. Is mbedtls not an option for you ?

**Comment by liz3** [comment]
I can ask them. 
As soon as i do **not** need to specify a custom root cert(like it was the last time/currently?) mbedtls is fine.

**Comment by bsergean** [comment]
I have made it so that the system cert is loaded by default with mbedtls. So it should be easy to use and equivalent to openssl, in ea207d81992a9ef91cfc50fc6902ae4fdb705af0

Specifying a custom root cert should work equally well with both backends.

**Comment by liz3** [comment]
@bsergean YES. works fine. thanks a lot for the hard. work!!
image

**Pull request merged**
