### PR TITLE
Fix crash during closing on Windows

### PR DESCRIPTION
**Pull request by Dimon4eg**
It crashes when `createSocket` fails to create socket on Windows because no SSL support.

Would be good to simulate error when creating socket.
@bsergean how to do that?

### CODE REVIEW

**Comment by bsergean** [comment]
The gcc + tsan ci is failing

https://travis-ci.com/machinezone/IXWebSocket/jobs/199426682

It should be possible to reproduce the problem locally if you have docker installed.

**Comment by bsergean** [comment]
I think that the background thread is still active not fully joined, but we are doing some work on the main/control thread which is closing.

It's a race condition between the 2 threads I believe.

**Comment by bsergean** [comment]
I checked out your branch and like your new code structure better than the previous one.
I have small comments but I'll do them myself without changing much.

If we want to override the 'socket creation', maybe we could have a factory to do that. But I don't know if that's really worth it ... we should probably add SSL support on Windows instead :)

**Comment by Dimon4eg** [comment]
SSL yes needed but in case would be good to have such test

**Comment by bsergean** [comment]
On another note, the unittest went from 10s to 22s to execute. Not sure what happened maybe it's more correct now, but it's annoying for developer productivity to wait a long time for unittest to finish.

Execution time: 22.27s

**Comment by bsergean** [comment]
Actually maybe it's because I'm on my home DSL which is bad.

**Comment by Dimon4eg** [comment]
On travis max execution time is 2:20 so it's your DSL is bad.
Why do you use it? :thinking: 
I thought it's dead nowadays.

**Comment by bsergean** [comment]
We have not updated our internet provider for a long time so we still have an old router from the ISP, but since it 'works' right now I prefer not to change it. Maybe one day.

**Pull request merged**
