### PR TITLE
add isEnabledAutomaticReconnection

### PR DESCRIPTION
**Pull request by Dimon4eg**

### CODE REVIEW

**Comment by Kumamon38** [comment]
Idk what is going on with the CI but
```
/Users/travis/build/machinezone/IXWebSocket/test/IXWebSocketPingTest.cpp:322: FAILED:
  REQUIRE( serverReceivedPingMessages == 1 )
with expansion:
  1 == 1
```
is becoming more and more strange
@bsergean

**Comment by bsergean** [comment]
@Kumamon38 yeah some tests aren't reliable, I wonder if we just broke something recently.

**Comment by Dimon4eg** [comment]
@bsergean you can merge this simple PR. CI fails on another tests

**Comment by bsergean** [comment]
I will, but can you first rename the api to *isAutomaticReconnectionEnabled()* ?

**Comment by bsergean** [comment]
Thanks !

**Pull request merged**
