### PR TITLE
fix close code/reason issue

### PR DESCRIPTION
**Pull request by Kumamon38**
Fix issue #33

- When `close(code, reason, wireSize)` is called, we use the close code, the close reason and send the close frame using these value, and after get back to default value.
- When the connection is closed without CLOSE frame, we use `1006` / `Abnormal closure`
- In all other cases (`setReadyState(CLOSED)`) and by default, code `1011` /  `"Internal error"` are sent when the connection is closed

### CODE REVIEW

**Comment by bsergean** [comment]
Hey I have merged the other PR, but I wasn't too sure on which one to merge first.

Do you know how to resolve the conflicts for that one ?

**Comment by bsergean** [comment]
Trying to resolve the merge myself with github UI ...

**Comment by Kumamon38** [comment]
you can look at my branch real-ping-origin which is the merge of both PR

**Comment by bsergean** [comment]
Thanks. I was able to do the merge myself eventually.

**Comment by Kumamon38** [comment]
Great 👍 finally we removed a bug with the reason misread

**Pull request merged**
