### PR TITLE
Added support for setting custom ping messages with support for any 'ping' message type (binary ping message, text ping message)

### PR DESCRIPTION
**Pull request by YuHuanTin**

### CODE REVIEW

**Comment by bsergean** [comment]
```

D:\a\IXWebSocket\IXWebSocket\ws\ws.cpp(1589): error C2660: 'ix::WebSocket::ping': function does not take 1 arguments
D:\a\IXWebSocket\IXWebSocket\ixwebsocket\IXWebSocket.h(93): note: see declaration of 'ix::WebSocket::ping'
D:\a\IXWebSocket\IXWebSocket\ws\ws.cpp(1589): note: while trying to match the argument list '(const std::string)'
```

CI failed on windows with this error.

**Comment by YuHuanTin** [comment]
Forgot to be compatible with the previous ping function :)

**Comment by bsergean** [comment]
Ah hopefully that should fix it.

**Comment by bsergean** [comment]
merging, thanks for the pr !

**Pull request merged**
